name: Auto Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}

            echo ">>> Git pull"
            git pull

            echo ">>> Activate venv"
            if [ -d "venv" ]; then
              source venv/bin/activate
            fi

            echo ">>> Stop old process"
            pkill -f "main.py" || true

            echo ">>> Start new process"
            nohup python main.py > app.log 2>&1 &
